name: CI/CD — Laravel microservices to cPanel (multi-host)

on:
  push:
    branches: [develop, main]
    paths:
      - "**"
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    permissions:
      contents: read
    concurrency:
      group: deploy-${{ matrix.service }}-${{ github.ref_name }}
      cancel-in-progress: false
    strategy:
      fail-fast: false
      matrix:
        include:
          # --- Host 178.16.134.117 (uses default secrets) ---
          - service: Authentication_Service
            url: https://test-api-authentication-service.pick-a-part.ca
            migrate: false
            host: 178.16.134.117
          - service: Data_Amendment_Service
            url: https://test-api-amendment-service.pick-a-part.ca
            migrate: false
            host: 178.16.134.117
          - service: Encryption_Service
            url: https://test-api-encryption-service.pick-a-part.ca
            migrate: false
            host: 178.16.134.117
          - service: Files_Magangment_Service
            url: https://test-api-files-magangment-service.pick-a-part.ca
            migrate: false
            host: 178.16.134.117
          - service: Garage_Service
            url: https://test-api-garage-service.pick-a-part.ca
            migrate: false
            host: 178.16.134.117
          - service: Mailing_Service
            url: https://test-api-mailing-service.pick-a-part.ca
            migrate: false
            host: 178.16.134.117
          - service: Membership_Service
            url: https://test-api-membership-service.pick-a-part.ca
            migrate: false
            host: 178.16.134.117
          - service: Parts_Service
            url: https://test-api-parts-service.pick-a-part.ca
            migrate: false
            host: 178.16.134.117
          - service: Vendor_Service
            url: https://test-api-vendor-service.pick-a-part.ca
            migrate: false
            host: 178.16.134.117
          - service: Notification_Service
            url: https://test-api-notification-service.pick-a-part.ca
            migrate: false
            host: 178.16.134.117

          # --- Host 195.35.9.105 (override with *separate* secrets) ---
          - service: Managment_Service_Ca_Vds
            url: https://mgmt.api.yourdomain.com
            migrate: false
            host: ${{ secrets.CP2_HOST }} # e.g. 195.35.9.105
            user: ${{ secrets.CP2_USER }} # cPanel/SSH user for this host
            deploy_base: ${{ secrets.DEPLOY2_BASE }} # e.g. /home/other_user/apps
            ssh_key: ${{ secrets.CP2_SSH_KEY }} # optional (if different key)
          - service: Vendor_Service_Ca_Vds
            url: https://vendor-ca-vds.api.yourdomain.com
            migrate: false
            host: ${{ secrets.CP2_HOST }}
            user: ${{ secrets.CP2_USER }}
            deploy_base: ${{ secrets.DEPLOY2_BASE }}
            ssh_key: ${{ secrets.CP2_SSH_KEY }}

    env:
      SERVICE_DIR: ${{ matrix.service }}
      ENV_NAME: ${{ github.ref_name == 'main' && 'production' || 'staging' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Detect if THIS service changed between the previous commit on this ref and current
      - name: Detect changes for this service
        id: changes
        shell: bash
        run: |
          base="${{ github.event.before }}"
          if [ -z "$base" ]; then base=$(git rev-list --max-parents=0 HEAD); fi
          if git diff --name-only "$base"...HEAD | grep -E "^${{ env.SERVICE_DIR }}/" >/dev/null 2>&1; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Skip (no changes)
        if: steps.changes.outputs.changed == 'false' && github.event_name != 'workflow_dispatch'
        run: echo "No changes in ${{ env.SERVICE_DIR }} — skipping." && exit 0

      - name: Setup PHP (Composer)
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer:v2
          coverage: none

      # Pick project composer.phar if present, and print version
      - name: Select Composer & show version
        id: comp
        working-directory: ${{ env.SERVICE_DIR }}
        shell: bash
        run: |
          if [ -f composer.phar ]; then
            echo "Using project composer.phar"
            echo "composer_bin=php composer.phar" >> "$GITHUB_OUTPUT"
            php composer.phar -V
          else
            echo "Using runner Composer"
            echo "composer_bin=composer" >> "$GITHUB_OUTPUT"
            composer -V
          fi

      - name: Composer install (no-dev) — ${{ env.SERVICE_DIR }}
        working-directory: ${{ env.SERVICE_DIR }}
        run: ${{ steps.comp.outputs.composer_bin }} install --no-dev --prefer-dist --optimize-autoloader --no-interaction

      # Optional Node build (only if package.json exists)
      - name: Setup Node (optional)
        if: hashFiles(format('{0}/package.json', env.SERVICE_DIR)) != ''
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: ${{ env.SERVICE_DIR }}/package-lock.json

      - name: Build assets (optional)
        if: hashFiles(format('{0}/package.json', env.SERVICE_DIR)) != ''
        working-directory: ${{ env.SERVICE_DIR }}
        run: |
          npm ci
          npm run build || echo "No build script; skipping"

      - name: Exclude list for rsync
        run: |
          cat > exclude.txt <<'EOF'
          .git/
          .github/
          node_modules/
          tests/
          storage/logs/*
          storage/framework/cache/*
          storage/framework/sessions/*
          storage/framework/views/*
          .env
          .env.*
          EOF

      - name: Setup SSH key (supports alternate key per service)
        run: |
          KEY_CONTENT="${{ matrix.ssh_key }}"
          if [ -z "$KEY_CONTENT" ]; then KEY_CONTENT="${{ secrets.CP_SSH_KEY }}"; fi
          echo "$KEY_CONTENT" > key.pem
          chmod 600 key.pem

      - name: Compute remote vars (fallback to default secrets)
        id: envs
        shell: bash
        run: |
          HOST="${{ matrix.host }}"
          USER="${{ matrix.user }}"
          BASE="${{ matrix.deploy_base }}"
          # fall back to repo secrets when not set in matrix
          HOST="${HOST:-${{ secrets.CP_HOST }}}"
          USER="${USER:-${{ secrets.CP_USER }}}"
          BASE="${BASE:-${{ secrets.DEPLOY_BASE }}}"
          echo "host=$HOST" >> $GITHUB_OUTPUT
          echo "user=$USER" >> $GITHUB_OUTPUT
          echo "remote_dir=$BASE/${{ env.SERVICE_DIR }}" >> $GITHUB_OUTPUT

      - name: Rsync to remote
        run: |
          rsync -az --delete \
            -e "ssh -i key.pem -o StrictHostKeyChecking=no" \
            --exclude-from=exclude.txt \
            "./${SERVICE_DIR}/" \
            "${{ steps.envs.outputs.user }}@${{ steps.envs.outputs.host }}:${{ steps.envs.outputs.remote_dir }}/"

      - name: Remote artisan (cache + migrate + storage:link)
        run: |
          SSH="ssh -i key.pem -o StrictHostKeyChecking=no ${{ steps.envs.outputs.user }}@${{ steps.envs.outputs.host }}"
          $SSH "bash -lc '
            set -e
            cd ${{ steps.envs.outputs.remote_dir }}

            PHP_CLI=php
            if ! command -v \$PHP_CLI >/dev/null 2>&1; then
              if [ -x /opt/cpanel/ea-php82/root/usr/bin/php ]; then
                PHP_CLI=/opt/cpanel/ea-php82/root/usr/bin/php
              fi
            fi

            mkdir -p storage/framework/{cache,sessions,views} bootstrap/cache
            chmod -R ug+rw storage bootstrap/cache || true

            if [ \"${{ github.ref_name }}\" = \"main\" ]; then \$PHP_CLI artisan down || true; fi
            if [ ! -e public/storage ]; then \$PHP_CLI artisan storage:link || true; fi

            \$PHP_CLI artisan config:clear  || true
            \$PHP_CLI artisan route:clear   || true
            \$PHP_CLI artisan view:clear    || true
            \$PHP_CLI artisan optimize      || true

            if [ \"${{ matrix.migrate }}\" = \"true\" ]; then \$PHP_CLI artisan migrate --force || true; fi

            if \$PHP_CLI artisan | grep -q \"queue:restart\"; then \$PHP_CLI artisan queue:restart || true; fi
            if \$PHP_CLI artisan | grep -q \"horizon\"; then \$PHP_CLI artisan horizon:terminate || true; fi

            if [ \"${{ github.ref_name }}\" = \"main\" ]; then \$PHP_CLI artisan up || true; fi
          '"

      - name: Smoke check (skip if not HTTP URL)
        shell: bash
        run: |
          URL="${{ matrix.url }}"
          if [[ "$URL" =~ ^https?:// ]]; then
            curl -fsSL --max-time 25 "$URL" >/dev/null || \
              (echo "Smoke check failed for $URL" && exit 1)
          else
            echo "Skipping smoke check for non-HTTP URL: $URL"
          fi
